cache:
  paths:
  - vendor/

stages:
  - test

test:7.4:
  stage: test
  image: php:7.4
  before_script:
  - bash ci/docker_install.sh > /dev/null
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - php composer.phar install
  script:
  - phpunit --configuration phpunit.xml  --coverage-text --colors=never

include:
  - template: Dependency-Scanning.gitlab-ci.yml